### ISSUE TITLE
Continuously deploy to GH Pages

### ISSUE THREAD

**Issue by dcecile** [tacit-lang/tacit#6]
Web links:

- [CI comparison](https://strongloop.com/strongblog/node-js-travis-circle-codeship-compare/)
- [Deploying from CodeShip to GH Pages](https://www.drinkingcaffeine.com/auto-deploying-to-gh-pages-with-codeship/)
- [Semaphore](https://github.com/marketplace/semaphore)
- [AppVeyor](https://github.com/marketplace/appveyor)

### Tasks

- [x] Document deploy steps
- [x] Create `fmtCheck`
- [x] Set up GitHub Pages project
- [x] Create GitHub Pages README
- [x] Create non-dev HTML files
- [x] Set up links between HTML files
- [x] Set up [Shippable](http://www.shippable.com/) CI build
- [x] Disable Shippable CI for non-master branches (long-running branches can open PRs to get CI)
- [x] Enable Shippable CI [caching](http://docs.shippable.com/ci/caching/) (for SBT and dependencies)
- [x] Set up Shippable deploy to GitHub pages using [state](http://docs.shippable.com/platform/workflow/resource/state/) ([utils](http://docs.shippable.com/platform/tutorial/workflow/using-shipctl/#copy_file_to_resource_state)) and [runSh](http://docs.shippable.com/platform/workflow/job/runsh/#runsh)
- [x] Don't deploy `-dev` HTML files
- [x] Switch Shippable deploy to use [job state](http://docs.shippable.com/platform/tutorial/workflow/sharing-data-between-jobs/#sharing-state-between-successive-jobs) (not global state)
- [x] Fix PNG errors
- [x] Make sure Shippable deploy doesn't trigger for PRs
- [x] Fill in all GitHub project and organization links
- [ ] Add Shippable badge to README

**Comment by dcecile** [comment]
Problem with PNG file worked around with Base64 encoding -- to be reverted in #14.

**Comment by dcecile** [comment]
Note: failure [notifications](http://docs.shippable.com/platform/workflow/resource/notification/) not set up yet
